GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/15

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Tawanda",
    "subscribedToChannel": "Web Dev Simplified"
}

